"use client";
import{useEffect,useState}from"react";
export default function AdminClient(){
 const[rows,setRows]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[tab,setTab]=useState("attendance"),[msg,setMsg]=useState("");
 async function load(){const[a,u,l,s]=await Promise.all([fetch("/api/attendance"),fetch("/api/admin/users"),fetch("/api/admin/logs"),fetch("/api/staff")]);setRows(await a.json());setUsers(await u.json());setLogs(await l.json());setStaff(await s.json())}useEffect(()=>{load()},[]);
 async function edit(id:string,field:string,value:string){const r=await fetch("/api/admin/attendance/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[field]:value||null})});setMsg(r.ok?"Attendance corrected and audit logged.":(await r.json()).error||"Update failed");load()}
 async function addManager(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),email:f.get("email"),password:f.get("password"),age:f.get("age"),gender:f.get("gender")})});const j=await r.json();setMsg(r.ok?"Manager added successfully.":j.error||"Could not add manager");if(r.ok)e.currentTarget.reset();load()}
 async function removeManager(id:string){if(!confirm("Remove this manager? They will immediately lose access, while audit history remains."))return;const r=await fetch("/api/admin/users",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const j=await r.json();setMsg(r.ok?"Manager removed.":j.error||"Remove failed");load()}
 async function addStaff(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/staff",{method:"POST",body:f});const j=await r.json();setMsg(r.ok?`Staff added: ${j.staffCode}`:j.error||"Could not add staff");if(r.ok)e.currentTarget.reset();load()}
 async function removeStaff(staffCode:string){if(!confirm("Remove this staff member? Their historical attendance will remain."))return;const r=await fetch("/api/staff",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({staffCode})});setMsg(r.ok?"Staff removed.":(await r.json()).error||"Remove failed");load()}
 return <><header className="top"><div className="brand">VEG MANTRA<small>MOHAN NAGAR • OWNER ADMIN PANEL</small></div><button className="nav" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}}>Logout</button></header><main className="wrap"><div className="actions tabs"><button className="btn" onClick={()=>setTab("attendance")}>Attendance</button><button className="btn secondary" onClick={()=>setTab("staff")}>Staff & Managers</button><button className="btn secondary" onClick={()=>setTab("logs")}>Audit Log</button></div>{msg&&<div className="notice">{msg}</div>}
 {tab==="attendance"&&<div className="card"><h2>All Staff Attendance</h2><p className="muted">Owner-only corrections. Missing check-in appears as Absent; manager-marked absences include their reason.</p><div className="tableWrap"><table className="table"><thead><tr><th>Staff</th><th>Date</th><th>Check in</th><th>Check out</th><th>Marked by</th><th>Status / Reason</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.staff.staffCode} — {x.staff.name}</td><td>{new Date(x.date).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})}</td><td>{x.virtual?"—":<input type="datetime-local" value={x.checkIn?new Date(x.checkIn).toISOString().slice(0,16):""} onChange={e=>edit(x.id,"checkIn",e.target.value)}/>}</td><td>{x.virtual?"—":<input type="datetime-local" value={x.checkOut?new Date(x.checkOut).toISOString().slice(0,16):""} onChange={e=>edit(x.id,"checkOut",e.target.value)}/>}</td><td>{x.markedBy?.name||"—"}</td><td><b>{x.status}</b>{x.note&&<div className="muted">{x.note}</div>}</td></tr>)}</tbody></table></div></div>}
 {tab==="staff"&&<div className="grid">
 <div className="card"><h2>Add Staff</h2><form onSubmit={addStaff} encType="multipart/form-data"><input name="photo" type="file" accept="image/*" required/><input name="name" placeholder="Staff full name" required/><input name="age" type="number" min="14" max="100" placeholder="Age" required/><select name="gender" required><option value="">Select gender</option><option>Male</option><option>Female</option><option>Other</option></select><button className="btn">Add Staff & Generate ID</button></form></div>
 <div className="card"><h2>Staff Configuration</h2>{staff.map(s=><div className="person" key={s.id}><div className="personInfo">{s.photoData&&<img src={s.photoData} alt=""/>}<div><b>{s.staffCode} — {s.name}</b><div className="muted">Age {s.age} • {s.gender}</div></div></div><button className="btn danger" onClick={()=>removeStaff(s.staffCode)}>Remove Staff</button></div>)}</div>
 <div className="card"><h2>Add Manager</h2><p className="muted">One email can belong to only one account. Manager access is restricted to the approved cafe network.</p><form onSubmit={addManager}><input name="email" type="email" placeholder="Manager email" required/><input name="name" placeholder="Manager name" required/><input name="age" type="number" min="18" max="100" placeholder="Age" required/><select name="gender" required><option value="">Select gender</option><option>Male</option><option>Female</option><option>Other</option></select><input name="password" type="password" placeholder="Manager password (6+ characters)" minLength={6} required/><button className="btn">Add Manager</button></form><h3>Managers</h3>{users.filter(u=>u.role==="MANAGER"&&u.active).map(u=><div className="person" key={u.id}><div><b>{u.name}</b><div className="muted">{u.email} • Age {u.age} • {u.gender}</div></div><button className="btn danger" onClick={()=>removeManager(u.id)}>Remove</button></div>)}</div>
 </div>}
 {tab==="logs"&&<div className="card"><h2>Audit Log</h2><div className="tableWrap"><table className="table"><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Details</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{new Date(x.createdAt).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})}</td><td>{x.action}</td><td>{x.actor?.name||"System"}</td><td>{x.details||"—"}</td></tr>)}</tbody></table></div></div>}</main></>}
