"use client";
import{useEffect,useMemo,useState}from"react";

function istDateTimeLocal(value:string|null|undefined){if(!value)return"";const d=new Date(value);const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(d);const g=(t:string)=>p.find(x=>x.type===t)?.value||"";return `${g("year")}-${g("month")}-${g("day")}T${g("hour")}:${g("minute")}`}
function istDateKey(v:string|Date){return new Date(v).toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"})}
function todayKey(){return new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"})}

export default function AdminClient(){
 const[rows,setRows]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[tab,setTab]=useState("dashboard"),[msg,setMsg]=useState(""),[staffFilter,setStaffFilter]=useState("ALL"),[statusFilter,setStatusFilter]=useState("ALL"),[fromDate,setFromDate]=useState(""),[toDate,setToDate]=useState("");
 async function load(){try{const[a,u,l,s]=await Promise.all([fetch("/api/attendance",{cache:"no-store"}),fetch("/api/admin/users",{cache:"no-store"}),fetch("/api/admin/logs",{cache:"no-store"}),fetch("/api/staff",{cache:"no-store"})]);setRows(await a.json());setUsers(await u.json());setLogs(await l.json());setStaff(await s.json())}catch{setMsg("Unable to load dashboard data.")}}
 useEffect(()=>{void load()},[]);
 const realRows=useMemo(()=>rows.filter(x=>!x.virtual),[rows]),today=useMemo(()=>realRows.filter(x=>istDateKey(x.date)===todayKey()),[realRows]);
 const present=today.filter(x=>x.status==="PRESENT"||x.checkIn).length,checkedOut=today.filter(x=>x.checkOut).length,absent=today.filter(x=>x.status==="ABSENT").length;
 async function edit(id:string,field:string,value:string){const r=await fetch("/api/admin/attendance/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[field]:value||null})});setMsg(r.ok?"Attendance corrected in IST and audit logged.":(await r.json()).error||"Update failed");void load()}
 async function addManager(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),email:f.get("email"),password:f.get("password"),age:f.get("age"),gender:f.get("gender")})});const j=await r.json();setMsg(r.ok?"Manager added successfully.":j.error||"Could not add manager");if(r.ok)e.currentTarget.reset();void load()}
 async function removeManager(id:string){if(!confirm("Remove this manager? They will immediately lose access."))return;const r=await fetch("/api/admin/users",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const j=await r.json();setMsg(r.ok?"Manager removed.":j.error||"Remove failed");void load()}
 async function addStaff(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/staff",{method:"POST",body:f});const j=await r.json();setMsg(r.ok?`Staff added: ${j.staffCode}`:j.error||"Could not add staff");if(r.ok)e.currentTarget.reset();void load()}
 async function removeStaff(staffCode:string){if(!confirm("Remove this staff member? Historical attendance remains."))return;const r=await fetch("/api/staff",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({staffCode})});setMsg(r.ok?"Staff removed.":(await r.json()).error||"Remove failed");void load()}
 const filteredRows=rows.filter(x=>(staffFilter==="ALL"||x.staffId===staffFilter)&&(statusFilter==="ALL"||x.status===statusFilter)&&(!fromDate||istDateKey(x.date)>=fromDate)&&(!toDate||istDateKey(x.date)<=toDate));
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}
 const nav=[["dashboard","Dashboard","⌂"],["attendance","Attendance","◷"],["staff","Staff","♙"],["managers","Managers","♢"],["logs","Audit log","≡"]];
 return <div className="appShell">
  <aside className="sidebar"><div className="sideBrand"><img src="/veg-mantra-logo.svg" alt="Veg Mantra"/><div><b>VEG MANTRA</b><span>MOHAN NAGAR</span></div></div><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{icon}</i>{label}</button>)}</nav><div className="sideBottom"><span>OWNER PANEL</span><small>Staff attendance system</small><button onClick={logout}>↪ Sign out</button></div></aside>
  <main className="mainArea"><header className="topbar"><button className="mobileMenu" aria-label="Open menu" onClick={()=>document.body.classList.toggle("navOpen")}>☰</button><button className="menuClose" aria-label="Close menu" onClick={()=>document.body.classList.remove("navOpen")}>×</button><div><span className="eyebrow">VEG MANTRA • MOHAN NAGAR</span><h2>{tab==="dashboard"?"Dashboard":tab==="attendance"?"Attendance":tab==="staff"?"Staff":tab==="managers"?"Managers":"Audit log"}</h2></div><div className="ownerPill"><span className="ownerDot">O</span><span>Owner</span><b>⌄</b></div></header><div className="content">
 {msg&&<div className="notice">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
 {tab==="dashboard"&&<><section className="welcome"><div><span className="eyebrow">GOOD FOOD • HAPPY PEOPLE</span><h1>Welcome back, Owner <span>✦</span></h1><p>Manage your team, track attendance and keep Veg Mantra running smoothly.</p><div className="welcomeMeta">Today • {new Date().toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})}</div></div><div className="welcomeArt"><div className="leaf">☘</div><strong>Fresh<br/>Food<br/>& good vibes</strong></div></section>
 <div className="statGrid"><button onClick={()=>setTab("staff")} className="statCard"><span className="statIcon green">♙</span><div><small>Total staff</small><strong>{staff.length}</strong><em>{staff.length?"Active staff members":"No staff added yet"}</em></div><b>→</b></button><button onClick={()=>setTab("attendance")} className="statCard"><span className="statIcon yellow">◷</span><div><small>Present today</small><strong>{present}</strong><em>{today.length?"Attendance recorded":"No attendance yet"}</em></div><b>→</b></button><button onClick={()=>setTab("attendance")} className="statCard"><span className="statIcon blue">↪</span><div><small>Checked out</small><strong>{checkedOut}</strong><em>{checkedOut?"Completed shifts":"No one checked out"}</em></div><b>→</b></button><button onClick={()=>setTab("attendance")} className="statCard"><span className="statIcon red">!</span><div><small>Absent today</small><strong>{absent}</strong><em>{absent?"Needs attention":"No absences recorded"}</em></div><b>→</b></button></div>
 <div className="quickGrid"><button onClick={()=>setTab("attendance")} className="quick primary"><span>◷</span><div><b>Mark attendance</b><small>Check in / Check out / Absent</small></div>→</button><button onClick={()=>setTab("staff")} className="quick"><span>♙</span><div><b>Manage staff</b><small>Add / view / remove</small></div>→</button><button onClick={()=>setTab("attendance")} className="quick"><span>▤</span><div><b>View records</b><small>Attendance & filters</small></div>→</button><button onClick={()=>setTab("managers")} className="quick"><span>♢</span><div><b>Manage managers</b><small>Add / remove / view</small></div>→</button></div>
 <div className="dashboardGrid"><section className="panel"><div className="panelHead"><h3>Recent activity</h3><button onClick={()=>setTab("logs")}>View all →</button></div>{logs.slice(0,5).map(x=><div className="activity" key={x.id}><span className="activityIcon">✓</span><div><b>{x.action.replaceAll("_"," ")}</b><small>{x.actor?.name||"System"} • {new Date(x.createdAt).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})}</small></div></div>)}{!logs.length&&<div className="empty">No activity yet.</div>}</section><section className="panel"><div className="panelHead"><h3>Today's attendance</h3><button onClick={()=>setTab("attendance")}>View all →</button></div>{today.slice(0,5).map(x=><div className="miniRow" key={x.id}><div><b>{x.staff?.name||"Staff"}</b><small>{x.staff?.staffCode||""}</small></div><span className={x.checkOut?"pill done":x.status==="ABSENT"?"pill absent":"pill"}>{x.checkOut?"Complete":x.status}</span></div>)}{!today.length&&<div className="empty"><b>No attendance records today</b><span>When staff are checked in or out, records appear here.</span></div>}</section><section className="panel"><div className="panelHead"><h3>Staff overview</h3><button onClick={()=>setTab("staff")}>View all →</button></div>{staff.slice(0,5).map(s=><div className="miniRow" key={s.id}><div className="miniPerson">{s.photoData?<img src={s.photoData} alt=""/>:<span>{s.name?.[0]}</span>}<div><b>{s.name}</b><small>{s.staffCode}</small></div></div><span className="pill">Active</span></div>)}{!staff.length&&<div className="empty"><b>No staff added yet</b><span>Add staff members to start tracking attendance.</span><button onClick={()=>setTab("staff")} className="btn">+ Add staff</button></div>}</section></div></>}
 {tab==="attendance"&&<section className="panel fullPanel"><div className="panelHead"><div><h3>Staff attendance</h3><p className="muted">Filter records and correct attendance in IST.</p></div></div><div className="filterBar"><select value={staffFilter} onChange={e=>setStaffFilter(e.target.value)}><option value="ALL">All Staff</option>{staff.map(s=><option key={s.id} value={s.id}>{s.staffCode} — {s.name}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">All statuses</option><option value="PRESENT">Present</option><option value="ABSENT">Absent</option><option value="LATE">Late</option><option value="LEAVE">Leave</option></select><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} /><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)} /><button className="btn secondary" onClick={()=>{setStaffFilter("ALL");setStatusFilter("ALL");setFromDate("");setToDate("")}}>Clear</button></div><p className="muted count">{filteredRows.length} entries shown</p><div className="tableWrap"><table className="table"><thead><tr><th>Staff</th><th>Date</th><th>Check in</th><th>Check out</th><th>Marked by</th><th>Status / reason</th></tr></thead><tbody>{filteredRows.map(x=><tr key={x.id}><td><b>{x.staff?.name}</b><small>{x.staff?.staffCode}</small></td><td>{new Date(x.date).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})}</td><td>{x.virtual?"—":<input type="datetime-local" value={istDateTimeLocal(x.checkIn)} onChange={e=>edit(x.id,"checkIn",e.target.value)}/>}</td><td>{x.virtual?"—":<input type="datetime-local" value={istDateTimeLocal(x.checkOut)} onChange={e=>edit(x.id,"checkOut",e.target.value)}/>}</td><td>{x.markedBy?.name||"—"}</td><td><b>{x.status}</b>{x.note&&<small>{x.note}</small>}</td></tr>)}</tbody></table></div>{!filteredRows.length&&<div className="empty">No attendance entries match these filters.</div>}</section>}
 {tab==="staff"&&<div className="sectionGrid"><section className="panel"><div className="panelHead"><div><h3>Add staff</h3><p className="muted">Photo, name, age and gender. Staff ID is generated automatically.</p></div></div><form className="form" onSubmit={addStaff} encType="multipart/form-data"><label>Photo<input name="photo" type="file" accept="image/*" required/></label><label>Full name<input name="name" placeholder="Staff full name" required/></label><div className="formRow"><label>Age<input name="age" type="number" min="14" max="100" required/></label><label>Gender<select name="gender" required><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></label></div><button className="btn">+ Add staff & generate ID</button></form></section><section className="panel"><div className="panelHead"><div><h3>Current staff</h3><p className="muted">{staff.length} active staff member{staff.length===1?"":"s"}</p></div></div>{staff.map(s=><div className="personRow" key={s.id}>{s.photoData?<img src={s.photoData} alt=""/>:<div className="avatar">{s.name?.[0]}</div>}<div><b>{s.name}</b><small>{s.staffCode} • Age {s.age} • {s.gender}</small></div><button className="btn danger smallBtn" onClick={()=>removeStaff(s.staffCode)}>Remove</button></div>)}{!staff.length&&<div className="empty">No staff members yet. Add your first staff member above.</div>}</section></div>}
 {tab==="managers"&&<div className="sectionGrid"><section className="panel"><div className="panelHead"><div><h3>Add manager</h3><p className="muted">Managers can mark attendance only from the approved cafe network.</p></div></div><form className="form" onSubmit={addManager}><label>Name<input name="name" required placeholder="Manager name"/></label><label>Email<input name="email" type="email" required placeholder="manager@example.com"/></label><div className="formRow"><label>Age<input name="age" type="number" min="18" max="100" required/></label><label>Gender<select name="gender" required><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></label></div><label>Password<input name="password" type="password" minLength={6} required placeholder="6+ characters"/></label><button className="btn">+ Add manager</button></form></section><section className="panel"><div className="panelHead"><div><h3>Active managers</h3><p className="muted">Removing a manager immediately ends their access.</p></div></div>{users.filter(u=>u.role==="MANAGER"&&u.active).map(u=><div className="personRow managerRow" key={u.id}><div className="avatar manager">M</div><div><b>{u.name}</b><small>{u.email} • Age {u.age} • {u.gender}</small></div><button className="btn danger smallBtn" onClick={()=>removeManager(u.id)}>Remove</button></div>)}</section></div>}
 {tab==="logs"&&<section className="panel fullPanel"><div className="panelHead"><div><h3>Audit log</h3><p className="muted">Owner-visible history of management and attendance changes.</p></div></div><div className="tableWrap"><table className="table"><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Details</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{new Date(x.createdAt).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})}</td><td><b>{x.action}</b></td><td>{x.actor?.name||"System"}</td><td>{x.details||"—"}</td></tr>)}</tbody></table></div>{!logs.length&&<div className="empty">No audit events yet.</div>}</section>}
 </div></main></div>
}
