"use client";
import {useEffect,useState} from "react";
export default function ManagerClient(){
 const[staff,setStaff]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState(""),[search,setSearch]=useState("");
 async function load(){const[u,a]=await Promise.all([fetch("/api/staff"),fetch("/api/attendance")]);setStaff(await u.json());setRows(await a.json())}
 useEffect(()=>{load()},[]);
 async function mark(staffId:string,action:string){setMsg("");const r=await fetch("/api/attendance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({staffId,action})});const j=await r.json();setMsg(r.ok?"Attendance saved.":j.error||"Attendance failed");load()}
 const todayLabel=new Date().toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"});
 return <><header className="top"><div className="brand">VEG MANTRA<small>MOHAN NAGAR • MANAGER ATTENDANCE</small></div><button className="nav" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}}>Logout</button></header>
 <main className="wrap"><div className="card"><h2>Staff Attendance</h2><p className="muted">All staff information is shown here. Search or use the Staff ID to record attendance.</p><input placeholder="Search by Staff ID or name…" value={search} onChange={e=>setSearch(e.target.value)}/>{msg&&<p>{msg}</p>}
 {staff.filter(s=>(s.name+" "+s.staffCode).toLowerCase().includes(search.toLowerCase())).map(s=>{const today=rows.find(r=>r.staffId===s.id&&new Date(r.date).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})===todayLabel);return <div className="card" key={s.id} style={{margin:"12px 0",padding:14}}><div style={{display:"flex",gap:14,alignItems:"center",flexWrap:"wrap"}}>{s.photoData&&<img src={s.photoData} alt="" style={{width:64,height:64,objectFit:"cover",borderRadius:12}}/>}<div><b>{s.staffCode} — {s.name}</b><div className="muted">Age {s.age} • {s.gender}</div></div></div><div className="actions" style={{marginTop:12}}><button className="btn" disabled={!!today?.checkIn} onClick={()=>mark(s.id,"checkin")}>Check In by ID</button><button className="btn secondary" disabled={!today?.checkIn||!!today?.checkOut} onClick={()=>mark(s.id,"checkout")}>Check Out by ID</button><span className="muted">{today?.checkIn?new Date(today.checkIn).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata"}):"Not checked in"}{today?.checkOut?" → "+new Date(today.checkOut).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata"}):" • Not checked out"}</span></div></div>})}</div></main></>}
