"use client";
import{useEffect,useState}from"react";
export default function ManagerClient(){
 const[staff,setStaff]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState(""),[search,setSearch]=useState(""),[absent,setAbsent]=useState<any>(null),[reason,setReason]=useState("");
 async function load(){const[u,a]=await Promise.all([fetch("/api/staff"),fetch("/api/attendance")]);setStaff(await u.json());setRows(await a.json())}useEffect(()=>{load()},[]);
 async function mark(staffId:string,action:string,r=""){setMsg("");const res=await fetch("/api/attendance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({staffId,action,reason:r})});const j=await res.json();setMsg(res.ok?"Attendance saved successfully.":j.error||"Attendance failed");if(res.ok){setAbsent(null);setReason("")}load()}
 const todayLabel=new Date().toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"});
 const filtered=staff.filter(s=>(s.name+" "+s.staffCode).toLowerCase().includes(search.toLowerCase()));
 return <><header className="top"><div className="brand">VEG MANTRA<small>MOHAN NAGAR • MANAGER ATTENDANCE</small></div><button className="nav" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}}>Logout</button></header><main className="wrap"><div className="hero"><div><span className="eyebrow">TODAY • IST</span><h1>Staff Attendance</h1><p className="muted">Search by name or Staff ID and record today's attendance.</p></div></div>{msg&&<div className="notice">{msg}</div>}<div className="card searchCard"><input placeholder="Search Staff ID or name…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{filtered.map(s=>{const today=rows.find(r=>r.staffId===s.id&&new Date(r.date).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})===todayLabel);const recorded=!!today&&!today.virtual;return <div className="card staffCard" key={s.id}><div className="personInfo">{s.photoData&&<img src={s.photoData} alt=""/>}<div><span className="staffId">{s.staffCode}</span><h3>{s.name}</h3><div className="muted">Age {s.age} • {s.gender}</div></div></div><div className="actions attendanceActions"><button className="btn" disabled={recorded||!!today?.checkIn} onClick={()=>mark(s.id,"checkin")}>Check In</button><button className="btn secondary" disabled={!today?.checkIn||!!today?.checkOut} onClick={()=>mark(s.id,"checkout")}>Check Out</button><button className="btn danger" disabled={recorded} onClick={()=>{setAbsent(s);setReason("")}}>Mark Absent</button></div><div className="attendanceState">{today?.status==="ABSENT"&&recorded?<><b>Absent</b>{today.note&&<span>Reason: {today.note}</span></>:today?.checkIn?<span>Checked in {new Date(today.checkIn).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata"})}{today.checkOut?" • Checked out "+new Date(today.checkOut).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata"}):" • Not checked out"}</span>:<span>Not recorded</span>}</div></div>})}
 {absent&&<div className="modalBackdrop"><div className="modal card"><h2>Mark {absent.name} absent</h2><p className="muted">{absent.staffCode} • A reason is required and will be recorded in the Owner audit/attendance panel.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Enter reason for absence…" rows={4}/><div className="actions"><button className="btn secondary" onClick={()=>setAbsent(null)}>Cancel</button><button className="btn danger" disabled={!reason.trim()} onClick={()=>mark(absent.id,"absent",reason.trim())}>Confirm Absent</button></div></div></div>}
 </main></>}
